### PR TITLE
feat: handle release candidate versions

### PR DESCRIPTION
**Pull request by domire8**
## Description

This PR changes the `compare-versions` action to allow and verify `-rcX` suffixes to the versions. This should for example allow to release modulo as 5.0.0-rc1 and then commit to it as 5.0.0.

## Review guidelines

Estimated Time of Review: x minutes

## Checklist before merging:

- [ ] Confirm that the relevant changelog(s) are up-to-date in case of any user-facing changes

### CODE REVIEW

**Review by LouisBrunner — COMMENTED** [review]
Maybe it would be better to handle prerelease tag in a more generic fashion?

**Comment by domire8** [comment]
> Maybe it would be better to handle prerelease tag in a more generic fashion?

How for example?

**Comment by LouisBrunner** [comment]
> How for example?

Instead of expecting `-rcX` as the prerelease tag, we could simply support semver-compliant versions and do the comparison directly. 

Maybe we could install one of this package to do the comparison:

* https://github.com/jceb/semver-compare-cli
* https://python-semver.readthedocs.io/en/2.9.0/cli.html

**Review by LouisBrunner — APPROVED** [review]
LGTM (if it works 😄)

**Comment by domire8** [comment]
Tested here

https://github.com/aica-technology/modulo/actions/runs/9838530258/job/27158773359

**Pull request merged**
