### PR TITLE
feat(ci): add list directories action

### PR DESCRIPTION
**Pull request by domire8**
## Description

A first small action that can be used to list directories with certain files. For example it can be used in HC to get the collections:
```yaml
- uses: aica-technology/.github/.github/actions/list-directories-containing-files@feature/list-directories
  id: list
  with:
    files: "(bake.hcl)"
```
or to get all packages in a repo (for changelog checks):
```yaml
- uses: aica-technology/.github/.github/actions/list-directories-containing-files@feature/list-directories
  id: list
  with:
    files: "(package.xml CMakeLists.txt)"
```

## Review guidelines

Estimated Time of Review: 5 minutes

### CODE REVIEW

**Comment by LouisBrunner** [comment]
I think we need an action like this but I was waiting for the real packaging system to come in before we roll it out. I am not sure why we need an extra listing for changelog checks though? Using `bake.hcl` you already know each package and can check if it has a changelog file and add to it there? Not sure we should have 2 ways to identify what a package is.

>       files: "(package.xml CMakeLists.txt)"

Might be better to use `"package.xml,CMakeLists.txt"` as this is how we do it everywhere else and it seems odd to use bash syntax there?

**Comment by domire8** [comment]
> Using `bake.hcl` you already know each package and can check if it has a changelog file and add to it there? Not sure we should have 2 ways to identify what a package is.

I was thinking that we'd have a CHANGELOG per ROS package. There is not one `bake.hcl` per ROS package, only per collection

**Comment by LouisBrunner** [comment]
> > Using `bake.hcl` you already know each package and can check if it has a changelog file and add to it there? Not sure we should have 2 ways to identify what a package is.
> 
> I was thinking that we'd have a CHANGELOG per ROS package. There is not one `bake.hcl` per ROS package, only per collection

But how does that translate to a changelog for the whole collection? We only tag the collections (as this is what gets released) not individual ROS packages?

**Comment by domire8** [comment]
Let's put this on hold for now, I did not have the right mindset at the beginning of the week

**Comment by domire8** [comment]
This is currently not needed, I will close this without merge

**Pull request closed without merging**
